// Generated by make_data.py from ../Data/PMMSY DEEP SEA FISHING VESSEL SCHEME 2020-2025.xlsx.
// Do not edit by hand: change the spreadsheet and run python3 make_data.py.
// Amounts in ₹ million; "ut" = union territory (no state share); null = not available.
window.RC_DATA = [
  {"key": "Gujarat", "sanctioned": 50, "built": 0, "total": 600.0, "central": 185.76, "state": null, "beneficiary": null},
  {"key": "Maharashtra", "sanctioned": 63, "built": 50, "total": 756.0, "central": 249.12, "state": 166.08, "beneficiary": 340.6},
  {"key": "Goa", "sanctioned": 0, "built": 0, "total": 0, "central": 0.0, "state": 0.0, "beneficiary": 0.0},
  {"key": "Karnataka", "sanctioned": 114, "built": 58, "total": 1368.0, "central": 354.24, "state": null, "beneficiary": null},
  {"key": "Kerala", "sanctioned": 20, "built": 6, "total": 240.0, "central": 57.6, "state": 38.4, "beneficiary": 144.0},
  {"key": "Tamil Nadu", "sanctioned": 0, "built": 0, "total": 0, "central": 0.0, "state": 0.0, "beneficiary": 0.0},
  {"key": "Andhra Pradesh", "sanctioned": 50, "built": 6, "total": 600.0, "central": 152.64, "state": 101.76, "beneficiary": 345.6},
  {"key": "Odisha", "sanctioned": 0, "built": 0, "total": 0, "central": 0.0, "state": 0.0, "beneficiary": 0.0},
  {"key": "West Bengal", "sanctioned": 0, "built": 0, "total": 0, "central": 0.0, "state": 0.0, "beneficiary": 0.0},
  {"key": "Andaman & Nicobar Islands", "sanctioned": 6, "built": 3, "total": 72.0, "central": 33.6, "state": "ut", "beneficiary": 33.6},
  {"key": "Lakshadweep", "sanctioned": 10, "built": 9, "total": 120.0, "central": 72.0, "state": "ut", "beneficiary": null},
  {"key": "Puducherry", "sanctioned": 9, "built": null, "total": 108.0, "central": 60.0, "state": "ut", "beneficiary": 48.0},
  {"key": "Daman & Diu", "sanctioned": 0, "built": 0, "total": 0, "central": 0.0, "state": 0.0, "beneficiary": 0.0}
];
