// Generated by make_data.py from PMMSY DEEP SEA FISHING VESSEL SCHEME 2020-2025_Update.xlsx.
// Do not edit by hand: change the spreadsheet and run python3 make_data.py.
// Amounts in ₹ million; sanctioned = boats approved, built = boats ordered (built or under
// construction); "ut" = union territory (no state share); null = data not available.
window.RC_DATA = [
  {"key": "Gujarat", "total": 600.0, "central": 185.76, "state": 123.84, "beneficiary": 290.4, "sanctioned": 50, "built": 0},
  {"key": "Maharashtra", "total": 756.0, "central": 249.12, "state": 166.08, "beneficiary": 340.8, "sanctioned": 63, "built": 49},
  {"key": "Goa", "total": 240.0, "central": 72.0, "state": 48.0, "beneficiary": 120.0, "sanctioned": 20, "built": 0},
  {"key": "Karnataka", "total": 1368.0, "central": 354.24, "state": null, "beneficiary": null, "sanctioned": 114, "built": 58},
  {"key": "Kerala", "total": 240.0, "central": 57.6, "state": 38.4, "beneficiary": 144.0, "sanctioned": 20, "built": 6},
  {"key": "Tamil Nadu", "total": 600.0, "central": 172.8, "state": 115.2, "beneficiary": 312.0, "sanctioned": 50, "built": 0},
  {"key": "Andhra Pradesh", "total": 600.0, "central": 152.64, "state": 101.76, "beneficiary": 345.6, "sanctioned": 50, "built": 6},
  {"key": "Odisha", "total": null, "central": null, "state": null, "beneficiary": null, "sanctioned": null, "built": null},
  {"key": "West Bengal", "total": 0.0, "central": 0.0, "state": 0.0, "beneficiary": 0.0, "sanctioned": 0, "built": 0},
  {"key": "Andaman & Nicobar Islands", "total": 72.0, "central": 33.6, "state": "ut", "beneficiary": 33.6, "sanctioned": 6, "built": 3, "flags": {"central": "*"}},
  {"key": "Lakshadweep", "total": 120.0, "central": 72.0, "state": "ut", "beneficiary": null, "sanctioned": 10, "built": 9},
  {"key": "Puducherry", "total": 108.0, "central": 60.0, "state": "ut", "beneficiary": null, "sanctioned": 9, "built": null},
  {"key": "Daman & Diu", "total": null, "central": null, "state": "ut", "beneficiary": null, "sanctioned": null, "built": null}
];
