#!/usr/bin/env python3
"""
Turns the reporter's spreadsheet into data.js for the interactive report card.

Amounts go from lakh to millions of rupees (10 lakh = ₹1 million).
Shares:
  - a number stays a number;
  - "nil (coz UT)" becomes "ut" (union territories have no state share);
  - any other text ("info not available", "complete info not available") becomes null.
Boat counts:
  - "nil" is 0;
  - "awaiting response" is null.
Editorial text (names, order, reasons) lives in content.js, not here.

    python3 make_data.py path/to/spreadsheet.xlsx

Without a path, it looks for ../Data/ beside this folder (the project folder layout). The spreadsheet holds the
reporter's raw notes, so it stays out of this repo.
"""
import json
import os
import sys

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
XLSX = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    HERE, "..", "Data", "PMMSY DEEP SEA FISHING VESSEL SCHEME 2020-2025.xlsx")
OUT = os.path.join(HERE, "data.js")
COLS = {"total": 2, "central": 3, "state": 4, "beneficiary": 5, "sanctioned": 7, "built": 8}  # C D E F H I


def cell(v):
    if isinstance(v, (int, float)):
        return float(v)
    s = str(v or "").strip().lower()
    if s.startswith("nil (coz ut)"):
        return "ut"
    if s == "nil":
        return 0.0
    return None


def million(v):
    return round(v / 10, 4) if isinstance(v, float) else v   # lakh -> ₹ million


def main():
    ws = openpyxl.load_workbook(XLSX, data_only=True).active
    rows = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if not r[1]:
            continue
        v = {k: cell(r[i]) for k, i in COLS.items()}
        rows.append({
            "key": r[1].strip(),                       # the spreadsheet's name; content.js maps it to a display name
            "sanctioned": int(v["sanctioned"] or 0),
            "built": None if v["built"] is None else int(v["built"]),
            "total": million(v["total"]) or 0,
            "central": million(v["central"]),
            "state": million(v["state"]),
            "beneficiary": million(v["beneficiary"]),
        })
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in rows)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Generated by make_data.py from PMMSY DEEP SEA FISHING VESSEL SCHEME 2020-2025.xlsx.\n"
                 "// Do not edit by hand: change the spreadsheet and run python3 make_data.py.\n"
                 "// Amounts in ₹ million; \"ut\" = union territory (no state share); null = not available.\n"
                 f"window.RC_DATA = [\n{body}\n];\n")

    # checks: shares that don't add up to the total, and the headline sums
    for r in rows:
        parts = [r[k] for k in ("central", "state", "beneficiary")]
        if r["total"] and all(isinstance(p, float) or p == "ut" for p in parts):
            gap = r["total"] - sum(p for p in parts if isinstance(p, float))
            if abs(gap) > 0.001:
                print(f"  ! {r['key']}: shares add up to ₹{r['total'] - gap:,.2f} million, not ₹{r['total']:,.2f} million")
    print(f"data.js: {len(rows)} rows; {sum(r['sanctioned'] for r in rows)} boats sanctioned, "
          f"{sum(r['built'] or 0 for r in rows)} built or under construction, "
          f"₹{sum(r['total'] for r in rows):,.1f} million sanctioned")


if __name__ == "__main__":
    main()
