#!/usr/bin/env python3
"""
Turns the reporter's spreadsheet into data.js for the interactive report card.

Reads the "final cleaned data sheet" layout (update of 30 Sep 2026):
  - a header row that starts with "State/Union Territory", then one row per state or union territory, up to the first
    empty row;
  - columns are found by their header text, so their order can change;
  - amounts are in ₹ million, as the header says ("in million ₹"). If the header says lakh, amounts are divided by 10.

Cells:
  - a number stays a number;
  - a number with an asterisk ("33.6*") keeps the asterisk as a footnote flag;
  - "Not applicable for a UT" becomes "ut" (union territories have no state share);
  - "Data not available", or any other text, becomes null.

In data.js, "sanctioned" is boats approved (2020-2025) and "built" is boats ordered, i.e. built or under construction
(September 2026). Editorial text (names, order, notes) lives in content.js, not here.

    python3 make_data.py path/to/spreadsheet.xlsx

The spreadsheet stays out of this repo.
"""
import json
import os
import re
import sys

import openpyxl

HERE = os.path.dirname(os.path.abspath(__file__))
XLSX = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    HERE, "..", "Data", "PMMSY DEEP SEA FISHING VESSEL SCHEME 2020-2025_Update.xlsx")
OUT = os.path.join(HERE, "data.js")
HEADERS = {  # field in data.js: words its column header contains
    "total": "total approved amount",
    "central": "central government share",
    "state": "state government share",
    "beneficiary": "beneficiary share",
    "sanctioned": "boats approved",
    "built": "boats ordered",
}


def cell(v):
    """(value, flag) for one cell."""
    if isinstance(v, (int, float)):
        return float(v), ""
    s = str(v or "").strip()
    m = re.fullmatch(r"([\d.,]+)\s*(\*+)", s)
    if m:
        return float(m.group(1).replace(",", "")), m.group(2)
    if s.lower().startswith("not applicable"):
        return "ut", ""
    return None, ""


def main():
    ws = openpyxl.load_workbook(XLSX, data_only=True).active
    rows = list(ws.iter_rows(values_only=True))
    head_i = next(i for i, r in enumerate(rows) if str(r[0] or "").strip().lower().startswith("state/union territory"))
    head = [str(h or "").strip().lower() for h in rows[head_i]]
    col = {k: next(i for i, h in enumerate(head) if words in h) for k, words in HEADERS.items()}
    scale = 0.1 if "lakh" in head[col["total"]] else 1.0

    out = []
    for r in rows[head_i + 1:]:
        if not str(r[0] or "").strip():
            break
        d, flags = {"key": str(r[0]).strip()}, {}
        for k, i in col.items():
            v, flag = cell(r[i])
            if isinstance(v, float) and k in ("sanctioned", "built"):
                v = int(v)
            elif isinstance(v, float):
                v = round(v * scale, 4)
            d[k] = v
            if flag:
                flags[k] = flag
        if flags:
            d["flags"] = flags
        out.append(d)

    body = ",\n".join("  " + json.dumps(d, ensure_ascii=False) for d in out)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(f"// Generated by make_data.py from {os.path.basename(XLSX)}.\n"
                 "// Do not edit by hand: change the spreadsheet and run python3 make_data.py.\n"
                 "// Amounts in ₹ million; sanctioned = boats approved, built = boats ordered (built or under\n"
                 "// construction); \"ut\" = union territory (no state share); null = data not available.\n"
                 f"window.RC_DATA = [\n{body}\n];\n")

    # checks: shares that don't add up to the total, and the headline sums
    for d in out:
        parts = [d[k] for k in ("central", "state", "beneficiary")]
        if isinstance(d["total"], float) and d["total"] and all(isinstance(p, float) or p == "ut" for p in parts):
            gap = d["total"] - sum(p for p in parts if isinstance(p, float))
            if abs(gap) > 0.001:
                note = " (flagged in the sheet)" if d.get("flags") else ""
                print(f"  ! {d['key']}: shares add up to ₹{d['total'] - gap:,.2f} million, not ₹{d['total']:,.2f} million{note}")
    known = [d for d in out if d["sanctioned"] is not None]
    print(f"data.js: {len(out)} rows from '{ws.title}'; {sum(d['sanctioned'] for d in known)} boats approved, "
          f"{sum(d['built'] or 0 for d in known)} ordered, ₹{sum(d['total'] or 0 for d in out):,.1f} million approved; "
          f"no data: {', '.join(d['key'] for d in out if d['sanctioned'] is None) or 'none'}")


if __name__ == "__main__":
    main()
